import { MAIN_TAB_ROUTES, ROOT_STACK_ROUTES } from './routes';

export const ROOT_STACK_ORDER = [ROOT_STACK_ROUTES.ONBOARDING, ROOT_STACK_ROUTES.MAIN_TABS] as const;

export const MAIN_TAB_ORDER = [
  MAIN_TAB_ROUTES.HOME,
  MAIN_TAB_ROUTES.WORKOUT,
  MAIN_TAB_ROUTES.HISTORY,
  MAIN_TAB_ROUTES.PROGRESS,
  MAIN_TAB_ROUTES.SETTINGS,
] as const;
